### ISSUE TITLE
consider integrating top-k planners for task planning

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#461] opened 2022-02-11 22:20 UTC
example: https://github.com/speckdavid/symk

**Comment by tomsilver** [comment] 2022-02-18 18:25
this one works better for our purposes: https://github.com/ctpelok77/kstar

**Comment by ronuchit** [comment] 2022-02-22 23:40
Code runs on the `topk` branch. To run it, first clone our fork of the kstar repo (https://github.com/ronuchit/kstar) at the same directory level as your predicators repo, then run `./build.py`.

We tried cover and blocks with debug grammar:
`python src/main.py --env cover --approach grammar_search_invention --seed 0 --grammar_search_use_handcoded_debug_grammar True --excluded_predicates all`
`python src/main.py --env blocks --approach grammar_search_invention --seed 0 --grammar_search_use_handcoded_debug_grammar True --excluded_predicates all`

Both work correctly, but are much slower than master:
```
master:
cover: Main script terminated in 46.27782 seconds
blocks: Main script terminated in 104.45043 seconds
topk:
cover: Main script terminated in 90.52044 seconds
blocks: Main script terminated in 145.83503 seconds
```
The evaluations for cover take around 7 seconds each for topk, but 0.1 seconds each for master. Upon investigation, we found that the issue is something related to time overhead from launching a shell process. You can see this discrepancy between "Total time" printed out by FD versus actual shell call time even in the example bundled with the kstar repo (run this command while in `kstar/`):
`time ./fast-downward.py examples/blocks/domain.pddl examples/blocks/probBLOCKS-9-2.pddl --search "kstar(lmcut(),k=5)"`

**Comment by ronuchit** [comment] 2022-02-23 00:03
closing in light of comment above

**Closed by ronuchit** 2022-02-23 00:03 UTC
